-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgw/JNBYxh5vj6GF8+M/WFBDX7GmrCZkucZiYd4GromKagCgYIKoZIzj0DAQehRANCAATeOGFoAv0YGXg7at4e9hrUUIMaHZEVmRDblJxb9V40N7/P1Rnw5HslR0J+oyrPIm/Ltz2keL+xdRrlhasK0xYs
-----END PRIVATE KEY-----